<?php
Class report extends  Act_Controller{
	public function __construct(){
		parent::__construct();
		$this->load->model("organization_main_model","orgmain");
	}
	
	function report_main(){
		$sql='SELECT 
PROVINCE_NAME,
(SELECT NVL(count("ORGAN_ID"),0) FROM ACT_ORGANIZATION_MAIN WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1)UNDER_TYPE_1,
(SELECT NVL(count("ORGAN_ID"),0) FROM ACT_ORGANIZATION_MAIN WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 2)UNDER_TYPE_2,
(SELECT NVL(count("ORGAN_ID"),0) FROM ACT_ORGANIZATION_MAIN WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 3)UNDER_TYPE_3,
(SELECT NVL(count("ORGAN_ID"),0) FROM ACT_ORGANIZATION_MAIN WHERE PROVINCE_CODE = pcode)UNDER_TYPE_TOTAL
FROM 
(SELECT DISTINCT PROVINCE_CODE pcode, PROVINCE_NAME from ACT_PROVINCE WHERE PROVINCE_CODE <> 97 ORDER BY PROVINCE_NAME ASC)';
		$data['orgmains'] = $this->orgmain->get($sql,TRUE);
		$this->template->build('report/report_main',@$data);
	}
	
	function report1_1(){
		$sql="SELECT 
PROVINCE_NAME,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 1) service_1,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 2) service_2,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 3) service_3,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 4) service_4,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 5) service_5,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 6) service_6,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 7) service_7,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'service' AND ANSWER_ID = 8) service_8
FROM 
(SELECT DISTINCT PROVINCE_CODE pcode, PROVINCE_NAME from ACT_PROVINCE WHERE PROVINCE_CODE <> 97 ORDER BY PROVINCE_NAME ASC)";
		$data['orgmains'] = $this->orgmain->get($sql,TRUE);
		$this->template->build('report/report1_1',@$data);
	}
	
	function report1_2(){
		// $this->db->debug = true;
		$sql="SELECT 
PROVINCE_NAME,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 1) process_1,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 2) process_2,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 3) process_3,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 4) process_4,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 5) process_5,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 6) process_6,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 7) process_7,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'process' AND ANSWER_ID = 8) process_8
FROM 
(SELECT DISTINCT PROVINCE_CODE pcode, PROVINCE_NAME from ACT_PROVINCE WHERE PROVINCE_CODE <> 97 ORDER BY PROVINCE_NAME ASC)";
		$data['orgmains'] = $this->orgmain->get($sql,TRUE);
		$this->template->build('report/report1_2',@$data);
	}
	
	function report1_3(){
		$sql="SELECT 
PROVINCE_NAME,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 2) target_2,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 3) target_3,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 4) target_4,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 5) target_5,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 6) target_6,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 7) target_7,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 8) target_8,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 9) target_9,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 10) target_10,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 11) target_11,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 12) target_12,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 13) target_13,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 14) target_14,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 15) target_15,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 16) target_16,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 17) target_17,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 18) target_18,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 19) target_19,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 20) target_20,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 21) target_21,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'target' AND ANSWER_ID = 23) target_23
FROM 
(SELECT DISTINCT PROVINCE_CODE pcode, PROVINCE_NAME from ACT_PROVINCE WHERE PROVINCE_CODE <> 97 ORDER BY PROVINCE_NAME ASC)";
		$data['orgmains'] = $this->orgmain->get($sql,TRUE);	
		$this->template->build('report/report1_3',@$data);
	}

	function report1_4(){
		$sql="SELECT 
PROVINCE_NAME,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote' AND ANSWER_ID = 1) promote_1,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote' AND ANSWER_ID = 2) promote_2,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote' AND ANSWER_ID = 3) promote_3,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote' AND ANSWER_ID = 4) promote_4,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote' AND ANSWER_ID = 5) promote_5,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote' AND ANSWER_ID = 6) promote_6,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote' AND ANSWER_ID = 7) promote_7
FROM 
(SELECT DISTINCT PROVINCE_CODE pcode, PROVINCE_NAME from ACT_PROVINCE WHERE PROVINCE_CODE <> 97 ORDER BY PROVINCE_NAME ASC)";
		$data['orgmains'] = $this->orgmain->get($sql,TRUE);
		$this->template->build('report/report1_4',@$data);
	}

	function report1_5(){
		$sql="SELECT 
PROVINCE_NAME,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote_get' AND ANSWER_ID = 1) promote_get_1,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote_get' AND ANSWER_ID = 2) promote_get_2,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote_get' AND ANSWER_ID = 3) promote_get_3,
(SELECT NVL(count('ANSWER_ID'),0) FROM ACT_ORGANIZATION_MAIN A LEFT JOIN ACT_ORGANIZATION_SUB S ON A.ORGAN_ID = S.ORGAN_ID WHERE PROVINCE_CODE = pcode AND UNDER_TYPE = 1 AND QUESTION_NAME = 'promote_get' AND ANSWER_ID = 4) promote_get_4
FROM 
(SELECT DISTINCT PROVINCE_CODE pcode, PROVINCE_NAME from ACT_PROVINCE WHERE PROVINCE_CODE <> 97 ORDER BY PROVINCE_NAME ASC)";
		$data['orgmains'] = $this->orgmain->get($sql,TRUE);
		$this->template->build('report/report1_5',@$data);
	}
}
?>